language: cpp
os:
  - windows
  - osx
  - linux
osx_image:
  - xcode12
  - xcode11.3
dist: bionic
addons:
  homebrew:
    packages:
      - jpeg-turbo
      - libpng
      - libtiff
    update: true
  apt:
    packages:
      - libjpeg-dev
      - libpng-dev
      - libtiff-dev
    update: true
before_script:
- |-
  case "$TRAVIS_OS_NAME"
    windows)
      cd extra
      ./build
      cd -
    ;;
  esac
script:
- |-
  case "$TRAVIS_OS_NAME"
    windows)
      mkdir build
      cd build
      cmake -A x64 -DCMAKE_INSTALL_PREFIX="C:\SAIL" -DSAIL_DEV=ON ..
      cmake --build . --config Release
    ;;
   osx | linux)
      mkdir build
      cd build
      cmake -DSAIL_DEV=ON ..
      cmake --build .
   ;;
  esac
